name: Build & Publish Minecraft Modpack
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Build modpack
        run: packwiz --pack-file ./configs/minecraft/modpack/pack.toml --meta-folder-base ./configs/minecraft/modpack modrinth export